package commands

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/zsying/loong"
	"github.com/zsying/loong/components/cli"
)

// New implements the `new` subcommand: it scaffolds a component
// source file.
type New struct {
	loong.Base
}

func (c *New) Run(ctx *loong.Scope) error {
	args, _ := ctx.Args.([]string)
	pos := cli.Positional(args)
	if len(pos) == 0 {
		return fmt.Errorf("cli new: missing component name (usage: cli new [--output=DIR|-o=DIR] <name>)")
	}
	name := pos[0]
	outDir := "."
	if d, ok := cli.Flag(args, "o", "output"); ok {
		outDir = d
	}
	src, err := scaffoldComponent(name)
	if err != nil {
		return err
	}
	out := filepath.Join(outDir, strings.ToLower(name)+".go")
	if err := os.WriteFile(out, []byte(src), 0o644); err != nil {
		return err
	}
	fmt.Printf("created %s\n", out)
	return nil
}

func init() {
	loong.RegisterComponent("cli.new", func() loong.Component { return &New{} },
		loong.WithDesc("scaffold a new component source file"),
	)
}

// scaffoldTemplate is the component skeleton generated by `loong new`.
// Placeholders: {{.Name}} (source identifier), {{.ID}} (yaml type).
const scaffoldTemplate = `package main

import (
	"github.com/zsying/loong"
	"github.com/zsying/loong/components/cli"
)

// {{.Name}}Config is the config block decoded from the config tree.
type {{.Name}}Config struct {
	// TODO: config keys, e.g. Port int with the yaml tag "port".
}

// {{.Name}} is the component.
type {{.Name}} struct {
	loong.Base
}

func (c *{{.Name}}) Build(ctx *loong.Scope) error {
	cfg, err := ctx.Config[{{.Name}}Config]()
	if err != nil {
		return err
	}
	_ = cfg
	// TODO: decode config, resolve services via ctx.Get[T](), subscribe
	// to child events via ctx.On(...).
	return nil
}

func init() {
	loong.RegisterComponent("{{.ID}}", func() loong.Component { return &{{.Name}}{},
		loong.WithConfig[{{.Name}}Config](),
		// loong.WithService(func(c loong.Component) *T { return ... }),
		// loong.WithEvents("domain.*"),
		loong.WithDesc("..."),
	)
}
`

type scaffoldData struct {
	Name string
	ID   string
}

func scaffoldComponent(name string) (string, error) {
	data := scaffoldData{
		Name: strings.ToLower(name[:1]) + name[1:], // camelCase
		ID:   "biz." + strings.ToLower(name),
	}
	t, err := template.New("component").Parse(scaffoldTemplate)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	if err := t.Execute(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}
