package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/zsying/loong"
)

// newCmd implements `loong new <name>`: it scaffolds a component
// source file.
type newCmd struct {
	loong.Base
}

func (c *newCmd) Run(*loong.Scope) error {
	if len(os.Args) < 3 {
		return fmt.Errorf("loong new: missing component name (usage: loong new <name>)")
	}
	name := os.Args[2]
	outDir := "."
	if i := indexOf(os.Args[3:], "-o"); i >= 0 && i+1 < len(os.Args[3:]) {
		outDir = os.Args[3:][i+1]
	}
	src, err := scaffoldComponent(name)
	if err != nil {
		return err
	}
	out := filepath.Join(outDir, strings.ToLower(name)+".go")
	if err := os.WriteFile(out, []byte(src), 0o644); err != nil {
		return err
	}
	fmt.Printf("created %s\n", out)
	return nil
}

func init() {
	loong.RegisterComponent("cli.new", func() loong.Component { return &newCmd{} },
		loong.WithDesc("scaffold a new component source file"),
	)
}

func indexOf(ss []string, want string) int {
	for i, s := range ss {
		if s == want {
			return i
		}
	}
	return -1
}

// scaffoldTemplate is the component skeleton generated by `loong new`.
// Placeholders: {{.Name}} (source identifier), {{.ID}} (yaml type).
const scaffoldTemplate = `package main

import (
	"github.com/zsying/loong"
)

// {{.Name}}Config is the config block decoded from the config tree.
type {{.Name}}Config struct {
	// TODO: config keys, e.g. Port int with the yaml tag "port".
}

// {{.Name}} is the component.
type {{.Name}} struct {
	loong.Base
}

func (c *{{.Name}}) Build(ctx *loong.Scope) error {
	cfg, err := ctx.Config[{{.Name}}Config]()
	if err != nil {
		return err
	}
	_ = cfg
	// TODO: decode config, resolve services via ctx.Get[T](), subscribe
	// to child events via ctx.On(...).
	return nil
}

func init() {
	loong.RegisterComponent("{{.ID}}", func() loong.Component { return &{{.Name}}{},
		loong.WithConfig[{{.Name}}Config](),
		// loong.WithService(func(c loong.Component) *T { return ... }),
		// loong.WithEvents("domain.*"),
		loong.WithDesc("..."),
	)
}
`

type scaffoldData struct {
	Name string
	ID   string
}

func scaffoldComponent(name string) (string, error) {
	data := scaffoldData{
		Name: strings.ToLower(name[:1]) + name[1:], // camelCase
		ID:   "biz." + strings.ToLower(name),
	}
	t, err := template.New("component").Parse(scaffoldTemplate)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	if err := t.Execute(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}
